Created works section
K-mone/mobile-setup-portfolio pull request #2
Opened 2023-09-23 12:24 UTC by K-mone

In this PR. I have completed the following tasks:
-Set up the linters for HTML and CSS
-Updated my README file
-Created the HTML file for works section and about me section
-Added the CSS file 
-Added the required photos
-Created the .gitignore file and added node modules to that file

2023-09-23 17:47 UTC, Rhaegar121 commented on style.css
> +  }
Remove `padding: 0 24px;` from the feature div to fix the white space problem as shown in the screenshot.

![Screenshot (178)](https://github.com/K-mone/mobile-setup-portfolio/assets/111948881/037c0e0b-4e64-4609-b9e1-5a47206572df)

2023-09-23 17:48 UTC, Rhaegar121 requested changes
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @K-mone  👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![close lady](https://user-images.githubusercontent.com/99246359/204822829-8d2e1877-0db5-435f-9e1e-438a33fc65d7.gif)

## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-23 17:49 UTC, Rhaegar121 commented on style.css
> +  }
Kindly remove `padding: 0 24px;` from the feature div to fix the white space problem as shown in screenshot.

![Uploading Screenshot (178).png…]()

2023-09-23 17:50 UTC, Rhaegar121 commented on style.css
>    }
Kindly remove `padding: 0 24px;` from the card-wrapper div too to fix the above problem.

2023-09-23 17:54 UTC, Rhaegar121 commented
Please kindly update your design to look exactly like the provided figma template.
`Your website should look exactly like the design (e.g. font, colors, images, text, margins) using the templates in Figma`

You can change your figma to developer mode in order to see the css code.

![Screenshot (170)](https://github.com/K-mone/mobile-setup-portfolio/assets/111948881/6e16a62c-8bce-4b67-a656-25fcfa4ef9ff)

2023-09-23 17:55 UTC, Rhaegar121 commented
I think you forgot about one requirement to add button interaction. **Kindly add this interaction to all your buttons.**

`Implement the button interactions (enable, hover, etc.)`

2023-09-23 17:56 UTC, Rhaegar121 commented
One last thing is to add the responsive design with `(min-width: 768px)` in your CSS. And implement the design according to the figma template as shown in the screenshot.

```
The website should be responsive, following these breakpoints:
Minimum mobile screen size should be 375px
Minimum desktop screen size should be 768px
Use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels
```
![Screenshot (179)](https://github.com/K-mone/mobile-setup-portfolio/assets/111948881/5af09141-4502-4e2c-abc3-38cf7fa5614b)

2023-09-27 16:40 UTC, DanielAD10 commented on index.html
> +        <div class="social-links">
I think you need to align the icon to the left as shown in figma.
And the gap between text and icon is too far. Please make sure the gap between text and icon to be the same.

2023-09-27 16:41 UTC, DanielAD10 requested changes
### STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️
---
Hi @K-mone 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Highlights 💯
---
No Linter errors ✔️
Descriptive Pull request summary✔️
Good commit messages ✔️
Professional Readme file ✔️

### Required Changes ♻️
---
Check the comments under the review.

_Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers, and Happy coding!**👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

2023-09-27 16:48 UTC, DanielAD10 commented
I think you need to align the icon to the left as shown in figma.
And the gap between text and icon is too far. Please make sure the gap between text and icon to be the same.

Your website should look exactly like the design (e.g. font, colors, images, text, margins) using the templates in Figma.

![ss1](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/e0dafc34-e262-48e1-a3fc-52d4e98ce167)     ![fig1](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/53e5b2f1-02c6-4364-9e4f-bfec7e417b93)

2023-09-30 13:17 UTC, DanielAD10 requested changes
I think you need to first to solve the Branch Conflict.

2023-09-30 13:40 UTC, DanielAD10 requested changes
###  STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @K-mone  👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![close lady](https://user-images.githubusercontent.com/99246359/204822829-8d2e1877-0db5-435f-9e1e-438a33fc65d7.gif)

## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-30 13:45 UTC, DanielAD10 commented
I think you need to fix the alignment in Multi Post Stories. Please make sure the HTML, CSS, JavaScript Button and See More Button are left align as in Figma.
![Screenshot (300)](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/84c830b0-1455-4314-8b00-0c1027d2355f)

2023-09-30 13:50 UTC, DanielAD10 commented
In your website, the color of HTML, Bootstrap, Ruby Button are not the same as Figma. And the See Project Button is not the same. Please make sure your website design layout is the same as Figma. 

This is from Figma 
![Screenshot (301)](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/1c7e22fc-9a77-4a48-bd43-21f055205053)

This is your design. 
![Screenshot (305)](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/f59faf0f-06e3-4054-a2b0-f10d6f6b3027)

2023-09-30 13:51 UTC, DanielAD10 commented
I think you need to add the line under the vector as in Figma.

![Screenshot (302)](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/16962709-217f-4780-ba4c-e4799815a284)

2023-09-30 13:54 UTC, DanielAD10 commented
I would like to tell you to make sure font size, font design and icon are the same as in Figma.


This is Figma Design.
![Screenshot (303)](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/bcea8bd5-ad6a-43a6-9c42-5d02c629f63d)

This is your website Design.
![Screenshot (304)](https://github.com/K-mone/mobile-setup-portfolio/assets/77822278/23986341-0cdc-4513-8f2e-4784026bf86b)

2023-10-01 02:05 UTC, DanielAD10 approved these changes
###  STATUS: APPROVED 🚦 ⚠️ ♻️ 

Hi @K-mone  👋, 

Good job so far!

## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-10-01 02:23 UTC, merged